import { Layout } from '@/components/layout';
import { GlobalProviderClient } from '@/providers/GlobalProviderClient';
import theme from '@/setting/theme/theme';
import { ThemeProvider } from '@mui/material';
import type { Metadata } from 'next';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { Inter } from 'next/font/google';
import 'react-json-view-lite/dist/index.css';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export interface RootLayout {
	children: React.ReactNode;
	params: { locale: string };
}

export const metadata: Metadata = {
	title: 'Albo agenda ',
	description: 'Generated by create next app'
};

export default function RootLayout(props: Readonly<RootLayout>) {
	const {
		children,
		params: { locale }
	} = props;

	const messages = useMessages();

	return (
		<html lang={locale}>
			<body className={inter.className}>
				<ThemeProvider theme={theme}>
					<NextIntlClientProvider locale={locale} messages={messages}>
						<GlobalProviderClient>
							<Layout>{children}</Layout>
						</GlobalProviderClient>
					</NextIntlClientProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
